### ISSUE TITLE
Unexpected error when running 'bionode'

### ISSUE THREAD

**Issue by tseemann** [bionode/bionode-ncbi#9] opened 2015-03-02 01:22 UTC
I did a global install of bionode, which installed ```/usr/bin/bionode``` in my ```$PATH```.

When I run "bionode" I get this error:

```
Please check the documentation at http://doc.bionode.io
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

Is this expected behaviour? 

I notice it downloaded and installed a bunch of tools, and I can see them in ```/usr/lib/node_modules/bionode/node_modules/``` including a subfolder ```bionode-ncbi``` but I don't have any tool called ```bionode-ncbi``` I can run?

I've never really used npm/Node software before, so any help appreciated.

**Comment by c089** [comment] 2015-04-03 20:20
Hi Torsten, first of all, sorry for the slow response!

> Is this expected behaviour?

Well... In a way ;) After reproducing and looking at the code I found that it's expected behavior, but a very unhelpful error message, which we should improve: `bionode-ncbi` expects you to pass some arguments, e.g. `bionode ncbi search taxonomy solenopsis`. See the README.md for more usage examples.

I hope this fixes your problem!

**Comment by tseemann** [comment] 2015-04-03 22:59
Do you want me to submit a new issue to improve the error message?

Here's some suggestions on improving the interface: http://www.gigasciencejournal.com/content/2/1/15

**Comment by c089** [comment] 2015-04-04 06:31
Thanks for the link. I talked to @bmpvieira last night about replacing the parser that is currently used for argument parsing so that we can easily have things like usage info, argument validation, etc. I'll create a new issue later, probably against bionode/bionode as this affects all sub-projects.

**Comment by bmpvieira** [comment] 2015-04-04 14:20
Thanks @tseemann. This is one of those obvious issues that should have been fixed by now but hasn't due to lack of time and also because of the minimal library used for parsing arguments ([minimist](http://github.com/substack/minimist)). As @c089 said, we'll switch to a more full-blown parser ([yargs](http://github.com/bcoe/yargs)) and add this.
 
Since it's not limited to `bionode-ncbi`, I'm closing this and you can follow the new issue at bionode/bionode#25.

In the meantime, you can check each module's [README.md](https://github.com/bionode/bionode-ncbi/blob/master/README.md#usage) which links to the documentation (e.g., [bionode-ncbi docs](http://rawgit.com/bionode/bionode-ncbi/master/docs/bionode-ncbi.html)) and the global docs at [doc.bionode.io](http://doc.bionode.io), resulting from the concatenation of all individual html docs (WIP: bionode/bionode#27).

**Closed by bmpvieira** 2015-04-04 14:20 UTC
